package com.sbs.loaney.data.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException
import com.sbs.loaney.R
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton

/** The user dismissed the Google account picker. Callers should fail silently, not show an error. */
class GoogleSignInCancelled : Exception("Google sign-in cancelled")

@Singleton
class GoogleAuthClient @Inject constructor(
    @ApplicationContext private val appContext: Context
) {
    private val credentialManager = CredentialManager.create(appContext)

    /**
     * Shows the Google account picker and returns an ID token to exchange for a Firebase credential.
     * The same call covers sign-up and sign-in: Firebase creates the account if the Google
     * identity is new, and signs into the existing one otherwise.
     *
     * [activityContext] must be an Activity — Credential Manager renders its bottom sheet on it.
     */
    suspend fun getIdToken(activityContext: Context): Result<String> {
        // default_web_client_id is generated by the google-services plugin from the client_type 3
        // entry in google-services.json. Google verifies the *Android* client separately, by
        // package name + signing certificate, so the SHA-1 must also be registered in Firebase.
        val serverClientId = appContext.getString(R.string.default_web_client_id)

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(GetSignInWithGoogleOption.Builder(serverClientId).build())
            .build()

        return try {
            val credential = credentialManager.getCredential(activityContext, request).credential

            if (credential is CustomCredential &&
                credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                Result.success(GoogleIdTokenCredential.createFrom(credential.data).idToken)
            } else {
                Result.failure(Exception("Unexpected credential type from Google"))
            }
        } catch (e: GetCredentialCancellationException) {
            Result.failure(GoogleSignInCancelled())
        } catch (e: NoCredentialException) {
            Result.failure(Exception("No Google account on this device. Add one in Settings, then try again."))
        } catch (e: GoogleIdTokenParsingException) {
            Result.failure(Exception("Could not read your Google account details. Please try again."))
        } catch (e: GetCredentialException) {
            // Overwhelmingly the cause here is a SHA-1 fingerprint that is not registered against
            // this package in the Firebase console, which surfaces as a generic provider failure.
            Result.failure(Exception("Google sign-in is unavailable right now. Please try another method."))
        }
    }
}
